create_section("apps/view?q=https://github.com/", "/files/assets/githublogo.png", "Github");
create_section("apps/view?q=https://win11.blueedge.me/", "/files/assets/windows.jpg", "Windows 11 in React");
create_section("apps/view?q=https://xp.quenq.com/", "/files/assets/windowsxp.png", "Windows XP");
create_section("apps/view?q=https://chatgpt.com/", "/files/assets/chatgpt-logo.jpg", "ChatGPT");
create_section("apps/view?q=https://www.twitch.tv/", "/files/assets/twitch-logo.png", "Twitch");
create_section("apps/view?q=https://discord.com/", "/files/assets/discord-logo.png", "Discord");
create_section("apps/view?q=https://open.spotify.com/", "/files/assets/spotify.png", "Spotify");
create_section("apps/view?q=https://plex.tv/", "/files/assets/plex.jpg", "Plex");
create_section("tools/view?q=https://freedns.afraid.org/", "/files/assets/freedns.png", "FreeDNS");
create_section("tools/view?q=https://extprint3r.github.io/printer.html", "/files/assets/extprint3r.png", "Extprint3r");
create_section("tools/view?q=https://thehomeworkai.com/", "/files/assets/hwai.png", "The Homework AI");
create_section("tools/view?q=https://math-gpt.org/", "/files/assets/mathai.png", "MathGPT");
create_section("tools/view?q=https://quillbot.com/", "/files/assets/quillbot.png", "Quillbot");
create_section("tools/view?q=https://vscode.dev/", "/files/assets/vscode.png", "VS Code");
create_section("/bots", "/files/assets/bot.png", "Bot Spammers");